---
stages:
  - "Code Quality"
  - "Data update"

.node_stage: &node_stage
  image: node:13-alpine
  before_script:
    - yarn --frozen-lockfile

Quality tests:
  <<: *node_stage
  stage: "Code Quality"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - yarn lint
    - yarn test

Data fetch:
  <<: *node_stage
  only:
    - master
  stage: "Data update"
  before_script:
    - yarn --frozen-lockfile
    - yarn global add npx
    - apk update && apk add git
    - git config user.name "Social Groovy Bot"
    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
    - git remote set-url origin https://${GH_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  script:
    - yarn fetch
    - |
      if [[ -n "$(git status -s ./data)" ]]; then
        echo "Files changed, checking JSON validity"
        # Check JSON files
        node -e "assert(require('./data/contributions.json').length > 0)" || {
          echo "Invalid JSON in $filename : no children"
          exit 1
        }
        echo "Commit files"
        # Commit files
        NOW=$(date +"%Y%m%d_%H%M")
        git add data
        git commit -m "feat(data): $NOW update"
        git push --no-verify origin HEAD:master
        npx semantic-release
      else
        echo "Nothing changed"
      fi

Force Publish:
  <<: *node_stage
  only:
    - master
  stage: "Data update"
  when: manual
  before_script:
    - yarn --frozen-lockfile
    - yarn global add npx
    - apk update && apk add git
    - git config user.name "Social Groovy Bot"
    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
    - git remote set-url origin https://${GH_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  script:
    - npx semantic-release
