---
stages:
  - "Code Quality"
  - "Data update"

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 5

.node_stage: &node_stage
  image: node:14-alpine
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - .yarn
  before_script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile --prefer-offline

Quality tests:
  <<: *node_stage
  stage: "Code Quality"
  script:
    - yarn lint
    - yarn check:types
    - yarn test

Data fetch:
  <<: *node_stage
  only:
    - alpha
    - beta
    - master
    - next
  stage: "Data update"
  variables:
    GIT_AUTHOR_EMAIL: 45039513+SocialGroovyBot@users.noreply.github.com
    GIT_AUTHOR_NAME: Social Groovy Bot
    GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
    GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
    GIT_DEPTH: 4242
  script:
    - yarn fetch

    - apk update && apk add git jq
    - |
      if [[ -z "$(git status -s ./data ./src)" ]]; then
        echo "Nothing changed"
        exit ${CI_JOB_SKIP_EXIT_CODE:-0}
      fi
    - |
      # Check JSON files
      echo "Files changed, checking JSON validity"
      node -e "assert(require('./data/contributions.json').length > 0)" || {
        echo "Invalid JSON in $filename : no children"
        exit 1
      }

    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - git pull --rebase
    - |
      echo "Commit files"
      # Commit files
      NOW=$(date +"%Y%m%d_%H%M")
      git add data
      git commit -m "feat(data): $NOW update"
      git push --no-verify origin HEAD:${CI_COMMIT_REF_NAME}

    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - yarn global add @semantic-release/changelog @semantic-release/exec @semantic-release/git
      semantic-release
    - $(yarn global bin)/semantic-release

Force Publish:
  <<: *node_stage
  only:
    - master
  stage: "Data update"
  when: manual
  variables:
    GIT_AUTHOR_EMAIL: 45039513+SocialGroovyBot@users.noreply.github.com
    GIT_AUTHOR_NAME: Social Groovy Bot
    GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
    GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
    GIT_DEPTH: 4242
  before_script:
    - apk update && apk add git jq
    - git remote set-url origin https://${GH_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - git pull --rebase
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn global add @semantic-release/changelog @semantic-release/exec @semantic-release/git
      semantic-release
    - $(yarn global bin)/semantic-release
